In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv("https://raw.githubusercontent.com/FlipRoboTechnologies/ML-Datasets/main/Grades/Grades.csv")
df.head()

,Seat No.,PH-121,HS-101,CY-105,HS-105/12,MT-111,CS-105,CS-106,EL-102,EE-119,...,CS-312,CS-317,CS-403,CS-421,CS-406,CS-414,CS-419,CS-423,CS-412,CGPA
0,CS-97001,B-,D+,C-,C,C-,D+,D,C-,B-,...,C-,C-,C-,C-,A-,A,C-,B,A-,2.205
1,CS-97002,A,D,D+,D,B-,C,D,A,D+,...,D+,D,C,D,A-,B-,C,C,B,2.008
2,CS-97003,A,B,A,B-,B+,A,B-,B+,A-,...,B,B,A,C,A,A,A,A-,A,3.608
3,CS-97004,D,C+,D+,D,D,A-,D+,C-,D,...,D+,C,D+,C-,B-,B,C+,C+,C+,1.906
4,CS-97005,A-,A-,A-,B+,A,A,A-,B+,A,...,B-,B+,B+,B-,A-,A,A-,A-,A,3.448

In [3]:
# delete seat no.
df=df.drop(['Seat No.'],axis=1)

In [4]:
df.shape

(571, 42)

In [5]:
# Each column cantain the correct data type

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 571 entries, 0 to 570
Data columns (total 42 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   PH-121     571 non-null    object
 1   HS-101     571 non-null    object
 2   CY-105     570 non-null    object
 3   HS-105/12  570 non-null    object
 4   MT-111     569 non-null    object
 5   CS-105     571 non-null    object
 6   CS-106     569 non-null    object
 7   EL-102     569 non-null    object
 8   EE-119     569 non-null    object
 9   ME-107     569 non-null    object
 10  CS-107     569 non-null    object
 11  HS-205/20  566 non-null    object
 12  MT-222     566 non-null    object
 13  EE-222     564 non-null    object
 14  MT-224     564 non-null    object
 15  CS-210     564 non-null    object
 16  CS-211     566 non-null    object
 17  CS-203     566 non-null    object
 18  CS-214     565 non-null    object
 19  EE-217     565 non-null    object
 20  CS-212     565 non-null    object
 21  CS-215     565 non-null    object
 22  MT-331     562 non-null    object
 23  EF-303     561 non-null    object
 24  HS-304     561 non-null    object
 25  CS-301     561 non-null    object
 26  CS-302     561 non-null    object
 27  TC-383     561 non-null    object
 28  MT-442     561 non-null    object
 29  EL-332     562 non-null    object
 30  CS-318     562 non-null    object
 31  CS-306     562 non-null    object
 32  CS-312     561 non-null    object
 33  CS-317     559 non-null    object
 34  CS-403     559 non-null    object
 35  CS-421     559 non-null    object
 36  CS-406     486 non-null    object
 37  CS-414     558 non-null    object
 38  CS-419     558 non-null    object
 39  CS-423     557 non-null    object
 40  CS-412     492 non-null    object
 41  CGPA       571 non-null    float64
dtypes: float64(1), object(41)
memory usage: 187.5+ KB

In [6]:
# Number of missing values are there

df.isnull().sum()

PH-121        0
HS-101        0
CY-105        1
HS-105/12     1
MT-111        2
CS-105        0
CS-106        2
EL-102        2
EE-119        2
ME-107        2
CS-107        2
HS-205/20     5
MT-222        5
EE-222        7
MT-224        7
CS-210        7
CS-211        5
CS-203        5
CS-214        6
EE-217        6
CS-212        6
CS-215        6
MT-331        9
EF-303       10
HS-304       10
CS-301       10
CS-302       10
TC-383       10
MT-442       10
EL-332        9
CS-318        9
CS-306        9
CS-312       10
CS-317       12
CS-403       12
CS-421       12
CS-406       85
CS-414       13
CS-419       13
CS-423       14
CS-412       79
CGPA          0
dtype: int64

In [7]:
for i in df:
    print(df[i].value_counts())

PH-121
A-    112
A     111
B+     61
B      57
B-     56
D      44
C      33
C+     31
D+     22
A+     22
C-     19
WU      2
F       1
Name: count, dtype: int64
HS-101
A-    82
B-    78
C     68
B     63
B+    59
C-    50
C+    47
D     45
A     38
D+    36
A+     4
F      1
Name: count, dtype: int64
CY-105
A     177
A-    120
B+     50
B      49
B-     42
D      31
A+     31
C      19
C+     17
C-     16
D+     14
WU      3
F       1
Name: count, dtype: int64
HS-105/12
A     96
A-    75
B+    70
B     57
D     45
C     41
B-    40
C+    39
C-    36
D+    34
A+    34
WU     2
F      1
Name: count, dtype: int64
MT-111
A-    105
A     100
B-     70
B+     62
B      55
C-     39
C+     33
C      30
D      26
A+     23
D+     21
WU      3
F       2
Name: count, dtype: int64
CS-105
A     151
A-    134
B+     60
B      51
A+     43
B-     38
C+     23
C      22
C-     22
D+     15
D      12
Name: count, dtype: int64
CS-106
A-    116
B+    101
B      96
A      56
B-     54
C+     41
D+     29
C-     27
D      24
C      18
A+      4
WU      2
F       1
Name: count, dtype: int64
EL-102
A-    105
A      92
B+     69
B      59
B-     53
D      38
C+     35
C-     32
C      30
A+     29
D+     23
WU      3
F       1
Name: count, dtype: int64
EE-119
A-    137
B+     83
B      77
A      68
B-     48
C      48
C+     38
D+     26
C-     26
D      11
A+      6
WU      1
Name: count, dtype: int64
ME-107
A-    79
A     77
B+    68
D     56
B-    56
B     50
C     49
C-    48
C+    37
D+    37
A+     8
WU     2
F      2
Name: count, dtype: int64
CS-107
A     105
A-     81
B+     57
B      55
C-     49
B-     43
A+     42
D      38
C+     34
D+     31
C      30
WU      2
I       1
F       1
Name: count, dtype: int64
HS-205/20
A-    150
A     118
B      97
B+     89
B-     36
C+     33
C      15
C-     11
D+      9
D       3
A+      2
F       2
WU      1
Name: count, dtype: int64
MT-222
A-    86
A     80
D     66
B     61
B-    52
D+    46
C     43
B+    42
C+    39
C-    30
A+    16
F      3
WU     1
W      1
Name: count, dtype: int64
EE-222
A     122
A-    121
B+     65
B      53
C      39
B-     35
A+     32
C+     29
D      25
D+     21
C-     16
F       4
W       2
Name: count, dtype: int64
MT-224
A-    120
A      80
B+     65
B      57
B-     49
C-     43
C+     39
D+     37
D      31
C      30
A+     10
WU      1
W       1
F       1
Name: count, dtype: int64
CS-210
A-    133
A     101
B+     84
B      59
B-     58
C      30
C+     27
C-     24
D+     21
D      12
A+     12
WU      1
W       1
F       1
Name: count, dtype: int64
CS-211
A-    68
A     67
B-    60
D+    56
B+    56
B     56
C+    55
C-    50
C     39
D     33
A+    21
F      3
WU     1
W      1
Name: count, dtype: int64
CS-203
A-    88
A     81
B     66
C+    62
B+    59
B-    53
D+    39
C     35
C-    35
D     30
A+    15
F      2
I      1
Name: count, dtype: int64
CS-214
C     76
A-    73
B     63
C-    57
B-    56
A     56
D+    47
C+    46
B+    45
D     31
A+    12
F      2
I      1
Name: count, dtype: int64
EE-217
A-    137
A      97
B+     70
B      63
B-     57
C      36
C+     29
A+     22
C-     20
D+     19
D      12
F       2
WU      1
Name: count, dtype: int64
CS-212
A-    101
B+     86
B      81
B-     65
C      44
A      43
D+     36
C+     35
C-     35
D      33
A+      4
WU      2
Name: count, dtype: int64
CS-215
A-    79
A     68
B     64
B-    59
C+    50
B+    50
C     48
C-    47
D     42
D+    38
A+    17
WU     1
W      1
F      1
Name: count, dtype: int64
MT-331
A     118
A-    103
B+     64
B      57
B-     46
C-     32
D+     31
A+     30
C      28
C+     27
D      22
F       4
Name: count, dtype: int64
EF-303
B     112
B-     92
C      61
B+     59
C+     58
C-     56
D+     49
A-     38
D      19
A      14
F       2
WU      1
Name: count, dtype: int64
HS-304
A-    128
B      72
B-     70
B+     66
C      58
C+     53
C-     33
A      28
D      20
D+     19
F       6
A+      4
WU      2
W       2
Name: count, dtype: int64
CS-301
A-    108
B+     74
B      71
A      66
B-     60
C      41
C+     37
C-     36
D      29
D+     29
A+      9
F       1
Name: count, dtype: int64
CS-302
A-    113
B     102
A      86
B+     81
B-     60
C+     32
C      28
D      21
C-     19
D+     10
A+      9
Name: count, dtype: int64
TC-383
A     105
A-     73
B+     68
B      59
C+     44
D+     44
C-     42
C      42
B-     40
A+     23
D      20
F       1
Name: count, dtype: int64
MT-442
A-    140
A     130
B+     65
B      47
A+     39
B-     30
C-     28
C+     24
C      24
D      20
D+     13
F       1
Name: count, dtype: int64
EL-332
A-    96
A     76
B+    68
B     67
B-    62
C     49
C+    38
C-    32
D+    22
D     22
A+    20
F      9
WU     1
Name: count, dtype: int64
CS-318
A-    89
B-    69
B     68
B+    65
C     53
C+    49
A     42
C-    40
D     36
D+    29
F     10
A+     6
WU     5
W      1
Name: count, dtype: int64
CS-306
A-    120
B+     75
A      74
B-     64
B      53
C-     40
C      37
C+     36
D      31
D+     18
A+     10
F       3
WU      1
Name: count, dtype: int64
CS-312
A+    93
A     86
A-    63
D+    52
C     48
C-    44
B+    42
B     37
C+    37
B-    36
D     19
F      2
W      1
WU     1
Name: count, dtype: int64
CS-317
B-    79
B     75
C     70
A-    66
B+    58
C+    57
A     47
C-    41
D+    34
D     16
A+     9
F      7
Name: count, dtype: int64
CS-403
A     133
A-    106
B+     62
B-     55
B      54
D+     35
C      33
C+     32
C-     30
A+     15
D       4
Name: count, dtype: int64
CS-421
B     86
B-    74
C     68
C+    61
C-    60
B+    60
A-    47
D+    36
A     25
D     21
F     17
A+     2
W      2
Name: count, dtype: int64
CS-406
A-    177
A      79
B+     64
B      58
B-     22
C+     22
C      19
D+     14
C-      8
A+      8
F       6
D       5
W       3
WU      1
Name: count, dtype: int64
CS-414
A     176
A-    156
B+     62
B      54
B-     21
A+     21
C+     21
C      20
C-     12
F       7
D+      3
D       3
W       2
Name: count, dtype: int64
CS-419
A-    120
B      89
B+     85
B-     78
A      56
C+     46
C      40
C-     20
D+     13
D       7
A+      2
F       2
Name: count, dtype: int64
CS-423
A-    122
A      78
B+     75
B      65
B-     56
C      45
C+     39
C-     29
D+     25
D      15
F       5
A+      3
Name: count, dtype: int64
CS-412
A-    157
B+     80
A      77
B      65
B-     37
C+     24
C      19
D+      8
C-      7
F       6
D       5
A+      4
W       3
Name: count, dtype: int64
CGPA
3.019    5
3.058    3
2.793    3
3.443    3
2.206    3
        ..
2.555    1
2.042    1
2.634    1
2.053    1
1.753    1
Name: count, Length: 491, dtype: int64

In [8]:
x=df.drop(['CGPA'],axis=1)
y=df.CGPA

In [9]:
# Now we will check of mode value of each column

for i in x:
    print(x[i].mode())

0    A-
Name: PH-121, dtype: object
0    A-
Name: HS-101, dtype: object
0    A
Name: CY-105, dtype: object
0    A
Name: HS-105/12, dtype: object
0    A-
Name: MT-111, dtype: object
0    A
Name: CS-105, dtype: object
0    A-
Name: CS-106, dtype: object
0    A-
Name: EL-102, dtype: object
0    A-
Name: EE-119, dtype: object
0    A-
Name: ME-107, dtype: object
0    A
Name: CS-107, dtype: object
0    A-
Name: HS-205/20, dtype: object
0    A-
Name: MT-222, dtype: object
0    A
Name: EE-222, dtype: object
0    A-
Name: MT-224, dtype: object
0    A-
Name: CS-210, dtype: object
0    A-
Name: CS-211, dtype: object
0    A-
Name: CS-203, dtype: object
0    C
Name: CS-214, dtype: object
0    A-
Name: EE-217, dtype: object
0    A-
Name: CS-212, dtype: object
0    A-
Name: CS-215, dtype: object
0    A
Name: MT-331, dtype: object
0    B
Name: EF-303, dtype: object
0    A-
Name: HS-304, dtype: object
0    A-
Name: CS-301, dtype: object
0    A-
Name: CS-302, dtype: object
0    A
Name: TC-383, dtype: object
0    A-
Name: MT-442, dtype: object
0    A-
Name: EL-332, dtype: object
0    A-
Name: CS-318, dtype: object
0    A-
Name: CS-306, dtype: object
0    A+
Name: CS-312, dtype: object
0    B-
Name: CS-317, dtype: object
0    A
Name: CS-403, dtype: object
0    B
Name: CS-421, dtype: object
0    A-
Name: CS-406, dtype: object
0    A
Name: CS-414, dtype: object
0    A-
Name: CS-419, dtype: object
0    A-
Name: CS-423, dtype: object
0    A-
Name: CS-412, dtype: object

In [10]:
# Now impute the null values by most frequest(Mode)

from sklearn.impute import SimpleImputer
sim_imp=SimpleImputer(strategy='most_frequent')
fill_null=sim_imp.fit_transform(x)
x=pd.DataFrame(fill_null)
x

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
0,B-,D+,C-,C,C-,D+,D,C-,B-,C-,...,C,C-,C-,C-,C-,A-,A,C-,B,A-
1,A,D,D+,D,B-,C,D,A,D+,D,...,D,D+,D,C,D,A-,B-,C,C,B
2,A,B,A,B-,B+,A,B-,B+,A-,A-,...,A-,B,B,A,C,A,A,A,A-,A
3,D,C+,D+,D,D,A-,D+,C-,D,C+,...,C-,D+,C,D+,C-,B-,B,C+,C+,C+
4,A-,A-,A-,B+,A,A,A-,B+,A,A-,...,A-,B-,B+,B+,B-,A-,A,A-,A-,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,B,A,A,A-,A+,A,A-,A-,A+,B+,...,B+,A-,A-,A,A,A,B+,B+,B,A
567,A+,A,A,A,A,A,A,A-,A,A,...,A-,B+,B+,A,A,A-,B,A-,C,A-
568,B,A,A-,B+,A,A,A,A,A,B,...,B+,A-,B,A,B+,A,C,B+,A-,A-
569,A,B+,D,A,D,D+,B-,C-,B-,C-,...,B+,D,B,B,C-,D,C,B,B-,C
570,C,D,D,C,C,D+,B,C+,C,D+,...,D+,C+,C,B-,D,F,C-,B+,D,C-

In [11]:
# All Null values has imputed 

x.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    0
35    0
36    0
37    0
38    0
39    0
40    0
dtype: int64

In [12]:
x=pd.DataFrame(sim_imp.fit_transform(x),columns=['PH-121','HS-101','CY-105', 'HS-105/12', 'MT-111', 'CS-105', 'CS-106', 'EL-102', 
                                                   'EE-119','ME-107', 'CS-107','HS-205/20', 'MT-222', 'EE-222', 'MT-224', 'CS-210',
                                                   'CS-211', 'CS-203', 'CS-214', 'EE-217','CS-212', 'CS-215', 'MT-331','EF-303',
                                                   'HS-304', 'CS-301', 'CS-302', 'TC-383', 'MT-442','EL-332','CS-318', 'CS-306', 
                                                   'CS-312', 'CS-317', 'CS-403', 'CS-421', 'CS-406','CS-414','CS-419', 'CS-423', 
                                                   'CS-412'])
x

,PH-121,HS-101,CY-105,HS-105/12,MT-111,CS-105,CS-106,EL-102,EE-119,ME-107,...,CS-306,CS-312,CS-317,CS-403,CS-421,CS-406,CS-414,CS-419,CS-423,CS-412
0,B-,D+,C-,C,C-,D+,D,C-,B-,C-,...,C,C-,C-,C-,C-,A-,A,C-,B,A-
1,A,D,D+,D,B-,C,D,A,D+,D,...,D,D+,D,C,D,A-,B-,C,C,B
2,A,B,A,B-,B+,A,B-,B+,A-,A-,...,A-,B,B,A,C,A,A,A,A-,A
3,D,C+,D+,D,D,A-,D+,C-,D,C+,...,C-,D+,C,D+,C-,B-,B,C+,C+,C+
4,A-,A-,A-,B+,A,A,A-,B+,A,A-,...,A-,B-,B+,B+,B-,A-,A,A-,A-,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,B,A,A,A-,A+,A,A-,A-,A+,B+,...,B+,A-,A-,A,A,A,B+,B+,B,A
567,A+,A,A,A,A,A,A,A-,A,A,...,A-,B+,B+,A,A,A-,B,A-,C,A-
568,B,A,A-,B+,A,A,A,A,A,B,...,B+,A-,B,A,B+,A,C,B+,A-,A-
569,A,B+,D,A,D,D+,B-,C-,B-,C-,...,B+,D,B,B,C-,D,C,B,B-,C
570,C,D,D,C,C,D+,B,C+,C,D+,...,D+,C+,C,B-,D,F,C-,B+,D,C-

In [13]:
from category_encoders import BinaryEncoder
bin_enc=BinaryEncoder()
x_tran=bin_enc.fit_transform(x)
x_tran

,PH-121_0,PH-121_1,PH-121_2,PH-121_3,HS-101_0,HS-101_1,HS-101_2,HS-101_3,CY-105_0,CY-105_1,...,CS-419_2,CS-419_3,CS-423_0,CS-423_1,CS-423_2,CS-423_3,CS-412_0,CS-412_1,CS-412_2,CS-412_3
0,0,0,0,1,0,0,0,1,0,0,...,0,1,0,0,0,1,0,0,0,1
1,0,0,1,0,0,0,1,0,0,0,...,1,0,0,0,1,0,0,0,1,0
2,0,0,1,0,0,0,1,1,0,0,...,1,1,0,0,1,1,0,0,1,1
3,0,0,1,1,0,1,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
4,0,1,0,0,0,1,0,1,0,1,...,0,1,0,0,1,1,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,0,1,1,0,1,0,1,0,0,0,...,1,0,0,0,0,1,0,0,1,1
567,1,1,0,0,1,0,1,0,0,0,...,0,1,0,0,1,0,0,0,0,1
568,0,1,1,0,1,0,1,0,0,1,...,1,0,0,0,1,1,0,0,0,1
569,0,0,1,0,1,0,0,0,1,0,...,0,0,0,1,0,1,1,0,0,1
570,1,0,0,0,0,0,1,0,1,0,...,1,0,1,0,1,0,0,1,1,0

In [14]:
x_tran.shape

(571, 164)

In [15]:
from sklearn.feature_selection import SelectKBest,f_classif

In [16]:
best_features= SelectKBest(score_func=f_classif,k=30)
fit=best_features.fit(x_tran,y)  
df_scores=pd.DataFrame(fit.scores_)
df_scores
df_columns=pd.DataFrame(x_tran.columns)
df_columns

            0
0    PH-121_0
1    PH-121_1
2    PH-121_2
3    PH-121_3
4    HS-101_0
..        ...
159  CS-423_3
160  CS-412_0
161  CS-412_1
162  CS-412_2
163  CS-412_3

[164 rows x 1 columns]

In [17]:
# concatenate dataframes

features_score=pd.concat([df_columns,df_scores],axis=1)
features_score

            0         0
0    PH-121_0  1.294285
1    PH-121_1  1.501412
2    PH-121_2  1.024871
3    PH-121_3  1.052563
4    HS-101_0  0.996959
..        ...       ...
159  CS-423_3  1.028157
160  CS-412_0  1.146657
161  CS-412_1  1.028432
162  CS-412_2  0.861658
163  CS-412_3  0.760755

[164 rows x 2 columns]

In [18]:
features_score.columns= ['Features_Name','Score']
X=features_score.nlargest(30,'Score') # It means find 50 largest features on the basis of score
print(X)

    Features_Name     Score
148      CS-414_0  2.707917
108      TC-383_0  1.820946
32       EE-119_0  1.646092
96       HS-304_0  1.624431
134      CS-317_2  1.577354
144      CS-406_0  1.564202
28       EL-102_0  1.558892
47    HS-205/20_3  1.555936
83       CS-212_3  1.529820
58       MT-224_2  1.522128
25       CS-106_1  1.507744
1        PH-121_1  1.501412
66       CS-211_2  1.497091
75       CS-214_3  1.488085
68       CS-203_0  1.473723
20       CS-105_0  1.452804
5        HS-101_1  1.443920
118      EL-332_2  1.443009
132      CS-317_0  1.428796
22       CS-105_2  1.415338
50       MT-222_2  1.391410
15    HS-105/12_3  1.377563
19       MT-111_3  1.374192
44    HS-205/20_0  1.355016
125      CS-306_1  1.342999
74       CS-214_2  1.337124
41       CS-107_1  1.335419
130      CS-312_2  1.309925
59       MT-224_3  1.305949
112      MT-442_0  1.295108

In [19]:
# Selected Feature
new_x=x_tran[['CS-414_0','TC-383_0','EE-119_0','HS-304_0','CS-317_2','CS-406_0','EL-102_0','HS-205/20_3','CS-212_3','MT-224_2',
        'CS-106_1','PH-121_1','CS-211_2','CS-214_3','CS-203_0','CS-105_0','HS-101_1','EL-332_2','CS-317_0','CS-105_2',
        'MT-222_2','HS-105/12_3','MT-111_3','HS-205/20_0','CS-306_1','CS-214_2','CS-107_1','CS-312_2','MT-224_3','MT-442_0']]
new_x

,CS-414_0,TC-383_0,EE-119_0,HS-304_0,CS-317_2,CS-406_0,EL-102_0,HS-205/20_3,CS-212_3,MT-224_2,...,MT-222_2,HS-105/12_3,MT-111_3,HS-205/20_0,CS-306_1,CS-214_2,CS-107_1,CS-312_2,MT-224_3,MT-442_0
0,0,0,0,0,0,0,0,1,1,0,...,0,1,1,0,0,0,0,0,1,0
1,0,0,0,0,1,0,0,0,0,1,...,1,0,0,0,0,0,0,1,0,0
2,0,0,0,0,1,0,0,1,1,1,...,1,1,1,0,0,1,0,1,1,0
3,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,1,1,0,0
4,0,0,0,0,0,0,0,1,1,0,...,1,0,1,0,0,1,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,0,1,1,0,1,0,0,1,0,1,...,0,1,1,0,1,1,0,0,1,0
567,0,1,0,0,0,0,0,1,1,1,...,0,0,1,0,0,0,0,1,0,0
568,0,1,0,0,1,0,0,0,1,1,...,0,0,1,0,1,1,0,0,0,0
569,0,0,0,1,1,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
570,1,0,1,1,0,1,1,0,0,1,...,1,1,0,0,0,1,0,1,0,0

In [20]:
from sklearn.preprocessing import StandardScaler

x_scaler=StandardScaler()
x_scaler=x_scaler.fit_transform(new_x)
x_scaler

array([[-0.30294918, -0.82726403, -0.51310266, ..., -1.29643788,
         0.83630423, -0.42684261],
       [-0.30294918, -0.82726403, -0.51310266, ...,  0.77134432,
        -1.19573711, -0.42684261],
       [-0.30294918, -0.82726403, -0.51310266, ...,  0.77134432,
         0.83630423, -0.42684261],
       ...,
       [-0.30294918,  1.20880391, -0.51310266, ..., -1.29643788,
        -1.19573711, -0.42684261],
       [-0.30294918, -0.82726403, -0.51310266, ..., -1.29643788,
        -1.19573711, -0.42684261],
       [ 3.30088372, -0.82726403,  1.94892774, ...,  0.77134432,
        -1.19573711, -0.42684261]])

In [21]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(new_x,y,test_size=0.20,random_state=20)

In [22]:
from sklearn.linear_model import LinearRegression
regression=LinearRegression()
regression.fit(x_train,y_train)

LinearRegression()

In [23]:
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error

In [38]:
print("*************Train Result************")
y_pred=regression.predict(x_train)
print("R2_Score", r2_score(y_train,y_pred))
print("Adjusted_R2_Score", regression.score(x_train,y_train))        
print("Mean Absolute Error", mean_absolute_error(y_train,y_pred))
print("Mean Square Error", mean_squared_error(y_train,y_pred))
print("Root Mean Square Error", np.sqrt(mean_squared_error(y_train,y_pred)))

pred=regression.predict(x_test)
print("***************Test Result************")
x1=r2_score(y_test,pred)
print("R2_Score", x1)
print("Adjusted_R2_Score", regression.score(x_test,y_test))  
print("Mean Absolute Error", mean_absolute_error(y_test,pred))
print("Mean Square Error", mean_squared_error(y_test,pred))
print("Root Mean Square Error", np.sqrt(mean_squared_error(y_test,pred)))

*************Train Result************
R2_Score 0.6978671725060457
Adjusted_R2_Score 0.6978671725060457
Mean Absolute Error 0.24062649356858506
Mean Square Error 0.11350678078085435
Root Mean Square Error 0.3369076739714522
***************Test Result************
R2_Score 0.6285997174738189
Adjusted_R2_Score 0.6285997174738189
Mean Absolute Error 0.3100048554297778
Mean Square Error 0.15558453070970474
Root Mean Square Error 0.3944420498751429

In [25]:
from sklearn.neighbors import KNeighborsRegressor
knn=KNeighborsRegressor()
knn.fit(x_train,y_train)

KNeighborsRegressor()

In [39]:
print("*************Train Result************")
y_pred=knn.predict(x_train)
print("R2_Score", r2_score(y_train,y_pred))
print("Adjusted_R2_Score", knn.score(x_train,y_train))        
print("Mean Absolute Error", mean_absolute_error(y_train,y_pred))
print("Mean Square Error", mean_squared_error(y_train,y_pred))
print("Root Mean Square Error", np.sqrt(mean_squared_error(y_train,y_pred)))

pred=knn.predict(x_test)
print("***************Test Result************")
x2=r2_score(y_test,pred)
print("R2_Score", x2)
print("Adjusted_R2_Score", knn.score(x_test,y_test))  
print("Mean Absolute Error", mean_absolute_error(y_test,pred))
print("Mean Square Error", mean_squared_error(y_test,pred))
print("Root Mean Square Error", np.sqrt(mean_squared_error(y_test,pred)))

*************Train Result************
R2_Score 0.7638849763067602
Adjusted_R2_Score 0.7638849763067602
Mean Absolute Error 0.21339517543859648
Mean Square Error 0.08870488008771929
Root Mean Square Error 0.29783364498947945
***************Test Result************
R2_Score 0.5878360274872205
Adjusted_R2_Score 0.5878360274872205
Mean Absolute Error 0.3147008695652174
Mean Square Error 0.17266098400000002
Root Mean Square Error 0.41552494991275796

In [27]:
from sklearn.tree import DecisionTreeRegressor
dec_Tree=DecisionTreeRegressor()
dec_Tree.fit(x_train,y_train)

DecisionTreeRegressor()

In [40]:
print("*************Train Result************")
y_pred=dec_Tree.predict(x_train)
print("R2_Score", r2_score(y_train,y_pred))
print("Adjusted_R2_Score", dec_Tree.score(x_train,y_train))        
print("Mean Absolute Error", mean_absolute_error(y_train,y_pred))
print("Mean Square Error", mean_squared_error(y_train,y_pred))
print("Root Mean Square Error", np.sqrt(mean_squared_error(y_train,y_pred)))

pred=dec_Tree.predict(x_test)
print("***************Test Result************")
x3=r2_score(y_test,pred)
print("R2_Score", x3)
print("Adjusted_R2_Score", dec_Tree.score(x_test,y_test))  
print("Mean Absolute Error", mean_absolute_error(y_test,pred))
print("Mean Square Error", mean_squared_error(y_test,pred))
print("Root Mean Square Error", np.sqrt(mean_squared_error(y_test,pred)))

*************Train Result************
R2_Score 1.0
Adjusted_R2_Score 1.0
Mean Absolute Error 0.0
Mean Square Error 0.0
Root Mean Square Error 0.0
***************Test Result************
R2_Score 0.47285203175218715
Adjusted_R2_Score 0.47285203175218715
Mean Absolute Error 0.362304347826087
Mean Square Error 0.22082931304347828
Root Mean Square Error 0.46992479509329815

In [29]:
from sklearn.ensemble import AdaBoostRegressor

ada=AdaBoostRegressor()
ada.fit(x_train,y_train)

AdaBoostRegressor()

In [41]:
print("*************Train Result************")
y_pred=ada.predict(x_train)
print("R2_Score", r2_score(y_train,y_pred))
print("Adjusted_R2_Score", ada.score(x_train,y_train))        
print("Mean Absolute Error", mean_absolute_error(y_train,y_pred))
print("Mean Square Error", mean_squared_error(y_train,y_pred))
print("Root Mean Square Error", np.sqrt(mean_squared_error(y_train,y_pred)))

pred=ada.predict(x_test)
print("***************Test Result************")
x4=r2_score(y_test,pred)
print("R2_Score", x4)
print("Adjusted_R2_Score", ada.score(x_test,y_test))  
print("Mean Absolute Error", mean_absolute_error(y_test,pred))
print("Mean Square Error", mean_squared_error(y_test,pred))
print("Root Mean Square Error", np.sqrt(mean_squared_error(y_test,pred)))

*************Train Result************
R2_Score 0.654442887395003
Adjusted_R2_Score 0.654442887395003
Mean Absolute Error 0.30177209789107157
Mean Square Error 0.12982063469586153
Root Mean Square Error 0.36030630676670306
***************Test Result************
R2_Score 0.5228016268413325
Adjusted_R2_Score 0.5228016268413325
Mean Absolute Error 0.3672387368618588
Mean Square Error 0.19990476161819326
Root Mean Square Error 0.4471071030728468

In [31]:
from sklearn.svm import SVR
svr=SVR()  
svr.fit(x_train,y_train)

SVR()

In [42]:
print("*************Train Result************")
y_pred=svr.predict(x_train)
print("R2_Score", r2_score(y_train,y_pred))
print("Adjusted_R2_Score", svr.score(x_train,y_train))        
print("Mean Absolute Error", mean_absolute_error(y_train,y_pred))
print("Mean Square Error", mean_squared_error(y_train,y_pred))
print("Root Mean Square Error", np.sqrt(mean_squared_error(y_train,y_pred)))

pred=svr.predict(x_test)
print("***************Test Result************")
x5=r2_score(y_test,pred)
print("R2_Score", x5)
print("Adjusted_R2_Score", svr.score(x_test,y_test))  
print("Mean Absolute Error", mean_absolute_error(y_test,pred))
print("Mean Square Error", mean_squared_error(y_test,pred))
print("Root Mean Square Error", np.sqrt(mean_squared_error(y_test,pred)))

*************Train Result************
R2_Score 0.9058985387289944
Adjusted_R2_Score 0.9058985387289944
Mean Absolute Error 0.10527865117623592
Mean Square Error 0.035352510431392335
Root Mean Square Error 0.1880226327636977
***************Test Result************
R2_Score 0.6673692236124497
Adjusted_R2_Score 0.6673692236124497
Mean Absolute Error 0.28627237097937114
Mean Square Error 0.13934346762435112
Root Mean Square Error 0.37328737940673956

In [53]:
from sklearn.model_selection import cross_val_score
reg_cros_score=cross_val_score(regression,x_scaler,y,cv=5).mean()
print("Cross Validation Score for each fold for Logical Regression", score, "\nAnd Mean Score " ,reg_cros_score)

Cross Validation Score for each fold for Logical Regression 0.6662291840319957
And Mean Score  0.6186737698067926

In [51]:
from sklearn.model_selection import cross_val_score
knn_cros_score=cross_val_score(knn,x_scaler,y,cv=5).mean()
print("Cross Validation Score for each fold for Logical Regression", score, "\nAnd Mean Score " ,knn_cros_score)

Cross Validation Score for each fold for Logical Regression 0.6662291840319957
And Mean Score  0.6030925468670387

In [50]:
from sklearn.model_selection import cross_val_score
dec_cros_score=cross_val_score(dec_Tree,x_scaler,y,cv=5).mean()
print("Cross Validation Score for each fold for Logical Regression", score, "\nAnd Mean Score " ,dec_cros_score)

Cross Validation Score for each fold for Logical Regression 0.6662291840319957
And Mean Score  0.15496634804196716

In [49]:
from sklearn.model_selection import cross_val_score
ada_cros_score=cross_val_score(ada,x_scaler,y,cv=5).mean()
print("Cross Validation Score for each fold for Logical Regression", score, "\nAnd Mean Score " ,ada_cros_score)

Cross Validation Score for each fold for Logical Regression 0.6662291840319957
And Mean Score  0.5294866342081699

In [47]:
from sklearn.model_selection import cross_val_score
svr_cros_score=cross_val_score(svr,x_scaler,y,cv=5).mean()
print("Cross Validation Score for each fold for Logical Regression", score, "\nAnd Mean Score " ,svr_cros_score)

Cross Validation Score for each fold for Logical Regression 0.6662291840319957
And Mean Score  0.6662291840319957

In [54]:
models = pd.DataFrame({'Model': ['Linear Regression','KNN','Decision Tree','AdaBoost','Support Vector Machines'],
                       'Model Test Result': [x1,x2,x3,x4,x5],
                       'Cross Validation Score' : [reg_cros_score,knn_cros_score,dec_cros_score,ada_cros_score,svr_cros_score]})
models

                     Model  Model Test Result  Cross Validation Score
0        Linear Regression           0.628600                0.618674
1                      KNN           0.587836                0.603093
2            Decision Tree           0.472852                0.154966
3                 AdaBoost           0.522802                0.529487
4  Support Vector Machines           0.667369                0.666229

In [60]:
# Save the data into file and share the path to the client.
import pickle
pickle.dump(models,open('Student_Grade','wb'))

In [61]:
# Client will load the file from the given path and go through the result.

pickle.load(open('Student_Grade','rb'))

                     Model  Model Test Result  Cross Validation Score
0        Linear Regression           0.628600                0.618674
1                      KNN           0.587836                0.603093
2            Decision Tree           0.472852                0.154966
3                 AdaBoost           0.522802                0.529487
4  Support Vector Machines           0.667369                0.666229

In [ ]:
# Support Vector Machine Model perform well